CREATE DATABASE IF NOT EXISTS prode_db;
USE prode_db;

CREATE TABLE IF not EXISTS partidos (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	local VARCHAR(50),
	visitante VARCHAR(50),
	estadio VARCHAR(50),
	ciudad VARCHAR(50),
	fecha VARCHAR(50),
	fase VARCHAR(50)
);
CREATE TABLE IF not EXISTS usuarios (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(60) NOT NULL,
	email VARCHAR(90) NOT NULL UNIQUE
);
