SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `prode` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_0900_ai_ci ;
USE `prode` ;

CREATE TABLE IF NOT EXISTS `prode`.`partido` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `equipo_local` VARCHAR(45) NOT NULL,
  `equipo_visitante` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `fase` ENUM('grupos', 'dieciseisavos', 'octavos', 'cuartos', 'semis', 'final') NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `prode`.`resultado` (
  `id_partido` INTEGER NOT NULL,
  `local` TINYINT NULL,
  `visitante` TINYINT NULL,
  PRIMARY KEY (`id_partido`),
  CONSTRAINT `fk_resultado_partido`
    FOREIGN KEY (`id_partido`)
    REFERENCES `prode`.`partido` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=1;
SET UNIQUE_CHECKS=1;